### ISSUE TITLE
tests: test generation

### ISSUE THREAD

**Issue by azjezz** [ryangjchandler/php-parser-rs#130]
the idea is to be able to just create `code.php`, and have a binary generate the other files containing either ast or errors.

would safe a big amount of time, since that ast struct would change pretty frequently now, and we don't want to have to re-write them over and over again.

**Comment by ryangjchandler** [comment]
yeah, I like this idea. Essentially snapshot testing, if I'm understanding you correctly.

**Comment by azjezz** [comment]
yes, while a generated test doesn't actually make sure things work as expected ( that is on the person who generated the test to verify ), it makes it easier to add tests, which are important in this project since it prevents regression ( things can break easily in parsers )
