### ISSUE TITLE
tests: `ast.json` instead `ast.txt`

### ISSUE THREAD

**Issue by azjezz** [ryangjchandler/php-parser-rs#131]
needs #129 

currently, we have `ast.txt` which contains a dump of the rust structure, it would be better if we have, `ast.json` containing the serialized nodes as a json object.

the problem with `ast.txt` is if there's a syntax error, we can't spot it until we run tests, but your editor would be able to spot a syntax error in a json file.

overall, it provides a much better experience when modifying the tests.

**Comment by ryangjchandler** [comment]
I think I'd prefer to use text instead of JSON, for consistency's sake. Rust can dump the tree natively without the need for `serde` etc, keeps it simple.
