### ISSUE TITLE
third party testing

### ISSUE THREAD

**Issue by azjezz** [ryangjchandler/php-parser-rs#132]
I was thinking about adding an integration test, that clones `azjezz/psl` and tries to parse every `.php` file in the project, this test will panic as soon as the parser fails to parse one of the files.

while PSL doesn't use that many quirky features ( syntax ) of PHP, it is a solid target that we can aim for, once `php-parser-rs` is able to completely parse it, we can consider it to be `beta`, where we start working on quirky features and edge cases.

**Comment by azjezz** [comment]
this will also give us kinda of a TODO list, the next task on the TODO will be the latest error we got while parsing PSL.

**Comment by ryangjchandler** [comment]
yeah, good idea. i was doing this on the Laravel framework, covers pretty much everything in the language at this point
